/* Generated By:JavaCC: Do not edit this line. RobotParserConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVE = 5;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 6;
  /** RegularExpression Id. */
  int T_PUTB = 7;
  /** RegularExpression Id. */
  int T_PICKB = 8;
  /** RegularExpression Id. */
  int T_PUTC = 9;
  /** RegularExpression Id. */
  int T_PICKC = 10;
  /** RegularExpression Id. */
  int ROBOT_R = 11;
  /** RegularExpression Id. */
  int VARS = 12;
  /** RegularExpression Id. */
  int BEGIN = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int Balloons = 15;
  /** RegularExpression Id. */
  int Chips = 16;
  /** RegularExpression Id. */
  int skip = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int REPEAT = 20;
  /** RegularExpression Id. */
  int TIMES = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int assing = 25;
  /** RegularExpression Id. */
  int move = 26;
  /** RegularExpression Id. */
  int turn = 27;
  /** RegularExpression Id. */
  int face = 28;
  /** RegularExpression Id. */
  int put = 29;
  /** RegularExpression Id. */
  int pick = 30;
  /** RegularExpression Id. */
  int to = 31;
  /** RegularExpression Id. */
  int of = 32;
  /** RegularExpression Id. */
  int toThe = 33;
  /** RegularExpression Id. */
  int inDir = 34;
  /** RegularExpression Id. */
  int rigth = 35;
  /** RegularExpression Id. */
  int left = 36;
  /** RegularExpression Id. */
  int around = 37;
  /** RegularExpression Id. */
  int north = 38;
  /** RegularExpression Id. */
  int south = 39;
  /** RegularExpression Id. */
  int east = 40;
  /** RegularExpression Id. */
  int west = 41;
  /** RegularExpression Id. */
  int facing = 42;
  /** RegularExpression Id. */
  int canPut = 43;
  /** RegularExpression Id. */
  int canPick = 44;
  /** RegularExpression Id. */
  int canMove = 45;
  /** RegularExpression Id. */
  int not = 46;
  /** RegularExpression Id. */
  int name = 47;
  /** RegularExpression Id. */
  int numero = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Move\"",
    "\"TURNRIGHT\"",
    "\"PutB\"",
    "\"PickB\"",
    "\"PutC\"",
    "\"PickC\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"Balloons\"",
    "\"Chips\"",
    "\"skip\"",
    "\"then\"",
    "\"do\"",
    "\"repeat\"",
    "\"times\"",
    "\"if\"",
    "\"while\"",
    "\"else\"",
    "\"assing\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"to\"",
    "\"of\"",
    "\"toThe\"",
    "\"inDir\"",
    "\"right\"",
    "\"left\"",
    "\"around\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMove\"",
    "\"not\"",
    "<name>",
    "<numero>",
    "\",\"",
    "\";\"",
    "\":\"",
  };

}
