/* Generated By:JavaCC: Do not edit this line. RobotParser.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import java.io.*;


@SuppressWarnings("serial")
public class RobotParser implements RobotParserConstants {


        private RobotWorldDec robotw;


        void setWorld(RobotWorld w) {
                robotw = (RobotWorldDec) w;
        }

    void delay(int d) {
                                try {
                                        Thread.sleep(d);
                                    } catch (InterruptedException e) {
                                        System.err.format("IOException: %s%n", e);
                                    }

    }

  final public boolean instructions(StringBuffer system) throws ParseException {
                                String output=new String();
    secuencia();
  }

  final public void secuencia() throws ParseException {
  Variable [] store = Variable[100];
    jj_consume_token(ROBOT_R);
    jj_consume_token(VARS);
    var();
    instrucion();
  }

  final public void var() throws ParseException {
    jj_consume_token(name);
    jj_consume_token(49);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case name:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(name);
    }

  }

  final public void instrucion() throws ParseException {
    jj_consume_token(BEGIN);
    intru();
    jj_consume_token(50);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case skip:
      case REPEAT:
      case IF:
      case WHILE:
      case assing:
      case move:
      case turn:
      case face:
      case put:
      case pick:
      case name:
      case numero:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      intru();
    }
  }

  final public void intru() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case skip:
    case assing:
    case move:
    case turn:
    case face:
    case put:
    case pick:
    case name:
    case numero:
      command();
      break;
    case REPEAT:
    case IF:
    case WHILE:
      controlStructure();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void command() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case assing:
      assing();
      break;
    case name:
    case numero:
      move();
      break;
    case turn:
      turn();
      break;
    case face:
      face();
      break;
    case put:
      put();
      break;
    case pick:
      pick();
      break;
    case move:
      moveTD();
      break;
    case skip:
      jj_consume_token(skip);

      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void assing() throws ParseException {
  int numero = 0;
  Token tokenNombre;
  Token tokenNumero;
  String nombre;
    jj_consume_token(assing);
    jj_consume_token(51);
    jj_consume_token(numero);
    jj_consume_token(to);
    jj_consume_token(51);
    jj_consume_token(name);
    tokenNombre = jj_consume_token(numero);
    tokenNumero = jj_consume_token(name);
        try
        {
          pNumero = Integer.parseInt(tokenNumero);

          Variable vacia = new Variable(pNumero, tokenNombre );

          for(int i = 0; i < store.length; i++)
          {
            if( store[i] == null)
            {
              store[i] = vacia;
            }
          }

        }
        catch(Exception e)
        {

        }
  }

  final public void move() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void turn() throws ParseException {
    jj_consume_token(turn);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case rigth:
      jj_consume_token(rigth);
      break;
    case left:
      jj_consume_token(left);
      break;
    case around:
      jj_consume_token(around);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void face() throws ParseException {
    jj_consume_token(face);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case north:
      jj_consume_token(north);
      break;
    case south:
      jj_consume_token(south);
      break;
    case east:
      jj_consume_token(east);
      break;
    case west:
      jj_consume_token(west);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void put() throws ParseException {
    jj_consume_token(put);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(of);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Balloons:
      jj_consume_token(Balloons);
      break;
    case Chips:
      jj_consume_token(Chips);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void pick() throws ParseException {
    jj_consume_token(pick);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(of);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Balloons:
      jj_consume_token(Balloons);
      break;
    case Chips:
      jj_consume_token(Chips);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void moveT() throws ParseException {
    jj_consume_token(toThe);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case rigth:
      jj_consume_token(rigth);
      break;
    case left:
      jj_consume_token(left);
      break;
    case around:
      jj_consume_token(around);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void moveD() throws ParseException {
    jj_consume_token(inDir);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case north:
      jj_consume_token(north);
      break;
    case south:
      jj_consume_token(south);
      break;
    case east:
      jj_consume_token(east);
      break;
    case west:
      jj_consume_token(west);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

//Move general
  final public void moveTD() throws ParseException {
    jj_consume_token(move);
    jj_consume_token(51);
    jj_consume_token(numero);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case toThe:
      moveT();
      break;
    case inDir:
      moveD();
      break;
    case name:
    case numero:
      move();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void controlStructure() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      conditional();
      break;
    case WHILE:
      loop();
      break;
    case REPEAT:
      RepeatTimes();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void conditional() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(51);
    condicion();
    jj_consume_token(THEN);
    jj_consume_token(51);
    intru();
    jj_consume_token(ELSE);
    intru();

  }

  final public void loop() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(51);
    condicion();
    jj_consume_token(51);
    intru();

  }

  final public void RepeatTimes() throws ParseException {
    jj_consume_token(REPEAT);
    jj_consume_token(51);
    intru();
    jj_consume_token(TIMES);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void condicion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case facing:
      facing();
      break;
    case canPut:
      canPut();
      break;
    case canPick:
      canPick();
      break;
    case canMove:
      canMove();
      break;
    case not:
      not();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void facing() throws ParseException {
    jj_consume_token(facing);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case north:
      jj_consume_token(north);
      break;
    case south:
      jj_consume_token(south);
      break;
    case east:
      jj_consume_token(east);
      break;
    case west:
      jj_consume_token(west);
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void canPut() throws ParseException {
    jj_consume_token(canPut);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(of);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Balloons:
      jj_consume_token(Balloons);
      break;
    case Chips:
      jj_consume_token(Chips);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void canPick() throws ParseException {
    jj_consume_token(canPick);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case numero:
      jj_consume_token(numero);
      break;
    case name:
      jj_consume_token(name);
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(of);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Balloons:
      jj_consume_token(Balloons);
      break;
    case Chips:
      jj_consume_token(Chips);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void canMove() throws ParseException {
    jj_consume_token(canMove);
    jj_consume_token(51);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case north:
      jj_consume_token(north);
      break;
    case south:
      jj_consume_token(south);
      break;
    case east:
      jj_consume_token(east);
      break;
    case west:
      jj_consume_token(west);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void not() throws ParseException {
    jj_consume_token(not);
    jj_consume_token(51);
    condicion();

  }

  /** Generated Token Manager. */
  public RobotParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x7ed20000,0x7ed20000,0x7e020000,0x0,0x0,0x0,0x0,0x18000,0x0,0x18000,0x0,0x0,0x0,0xd00000,0x0,0x0,0x0,0x0,0x18000,0x0,0x18000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x8000,0x18000,0x18000,0x18000,0x18000,0x38,0x3c0,0x18000,0x0,0x18000,0x0,0x38,0x3c0,0x18006,0x0,0x18000,0x7c00,0x3c0,0x18000,0x0,0x18000,0x0,0x3c0,};
   }

  /** Constructor with InputStream. */
  public RobotParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RobotParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RobotParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public RobotParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RobotParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public RobotParser(RobotParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 23; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
